services:
  install:
    # Image for installation
    image: ghcr.io/parkervcp/installers:debian
    # Mount the installation script and the data directory
    volumes:
      - ./data-install:/mnt/server
      - ./install.sh:/mnt/server/install.sh
    # Run the installation script
    command: /bin/bash /mnt/server/install.sh