name: Build and Push Docker Image FrankenPHP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 1,15 * *' # Run on the 1st and 15th of each month at 17:00 UTC
  push:
    branches:
      - master
    paths:
      frankenphp/**

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # Package tag name
  PACKAGE_TAG: frankenphp

permissions:
  actions: read
  packages: write
  pull-requests: write

concurrency:
  group: frankenphp${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "frankenphp-${{ matrix.php_version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version:
          - 8.2
          - 8.3
          - 8.4

    steps:
      # Track and monitor the workflow runs, jobs and steps resource metrics.
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          metric_frequency: 1
          proc_trace_sys_enable: true

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Login to ${{ env.REGISTRY }} Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image to the registry
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.PACKAGE_TAG }}
          file: ./${{ env.PACKAGE_TAG }}/Dockerfile
          push: true
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.PACKAGE_TAG }}-${{ matrix.php_version }}