name: Build and Push Docker Image NodeJS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 1,15 * *' # Run on the 1st and 15th of each month at 17:00 UTC
  push:
    branches:
      - master
    paths:
      nodejs/**

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # Package tag name
  PACKAGE_TAG: nodejs
  # Tag Name default value
  TAG_NAME: none

permissions:
  actions: read
  packages: write

concurrency:
  group: nodejs${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Login to ${{ env.REGISTRY }} Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set tag name based on condition
      - name: Set tag name
        id: set_tag_name
        run: |
          if [ "${{ matrix.tag }}" = "latest" ]; then
            echo "TAG_NAME=${{ env.PACKAGE_TAG }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ env.PACKAGE_TAG }}_${{ matrix.tag }}" >> $GITHUB_ENV
          fi

      # Build and push the Docker image to the registry
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.PACKAGE_TAG }}
          file: ./${{ env.PACKAGE_TAG }}/${{ matrix.tag }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.TAG_NAME }}