name: Build and Push Docker Image PHP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 1,15 * *' # Run on the 1st and 15th of each month at 17:00 UTC
  push:
    branches:
      - master
    paths:
      php/**

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # Package tag name
  PACKAGE_TAG: php

permissions:
  actions: read
  packages: write

concurrency:
  group: php${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "php${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 7.1
          - 7.1-nginx
          - 7.2
          - 7.2-nginx
          - 7.3
          - 7.3-nginx
          - 7.4
          - 7.4-nginx
          - "8.0"
          - 8.0-nginx
          - 8.1
          - 8.1-nginx
          - 8.2
          - 8.2-nginx
          - 8.3
          - 8.3-nginx
          - 8.4
          - 8.4-nginx

    steps:
      # Track and monitor the workflow runs, jobs and steps resource metrics.
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          metric_frequency: 1
          proc_trace_sys_enable: true

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Login to ${{ env.REGISTRY}} Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Cache Docker layers
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ runner.temp }}/.buildx-cache
      #     key: ${{ env.PACKAGE_TAG }}_${{ matrix.tag }}-${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ env.PACKAGE_TAG }}_${{ matrix.tag }}-${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.PACKAGE_TAG }}
          file: ./${{ env.PACKAGE_TAG }}/${{ matrix.tag }}/Dockerfile
          # cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          # cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max,compression=zstd,compression-level=22
          cache-from: type=gha
          cache-to: type=gha,mode=max,compression=zstd,compression-level=22
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.PACKAGE_TAG }}${{ matrix.tag }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      # - name: Move cache
      #   run: |
      #     rm -rf ${{ runner.temp }}/.buildx-cache
      #     mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache